spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/agileflow_db
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: true
server:
  port: 8080

jwt:
  secret: "CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_KEY_FOR_LOCAL_DEVELOPMENT_ONLY"
  access-token-expiration: 900000
  refresh-token-expiration: 2592000000
